[project]
name = "remotegraphdemo"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13.9"
dependencies = [
    "langchain>=1.2.0",
    "langchain-nvidia-ai-endpoints>=1.0.0",
    "langgraph-cli[inmem]>=0.4.11",
]
